- hosts: all
  become: true
  tasks: 
     - name: delete old deployment
       command: kubectl delete -f Deployment.yml --server https://192.168.49.2:8443
     #- name: delete old service
      # command: kubectl delete -f /home/ubuntu/Service.yml 
     #- name: create new deployment
      # command: kubectl apply -f /home/ubuntu/Deployment.yml
    # - name: create new service
     #  command: kubectl apply -f /home/ubuntu/Service.yml

