- hosts: all
  become: true
  tasks: 
    - name: create new deployment
      command: kubectl apply -f /home/ubuntu/Deployment.yml --server=https://192.168.49.2:8443
    - name: create new service
      command: kubectl apply -f /home/ubuntu/Service.yml --server=https://192.168.49.2:8443
