kind: Service
apiVersion: v1
metadata:
  name: g201210017
  labels:
    app: g201210017
spec:
  ports:
    - port: 80
      targetPort: 80
      nodePort: 80
  selector:
    app: g201210017
  type: LoadBalancer
